action config

diff --git a/.github/workflows/test-dotfiles.yaml b/.github/workflows/test-dotfiles.yaml
--- a/.github/workflows/test-dotfiles.yaml
+++ b/.github/workflows/test-dotfiles.yaml
@@ -39,8 +39,8 @@ jobs:
           ls -al $XDG_CONFIG_HOME
       - name: Validate core symlinks
         run: |
-          test -L $XDG_CONFIG_HOME/zsh/.zshrc || (echo "Missing .zshrc symlink" && exit 1)
-          test -L $XDG_CONFIG_HOME/.config/nvim/init.lua || (echo "Missing Neovim config" && exit 1)
+          test -L "$XDG_CONFIG_HOME/zsh/.zshrc" || (echo "Missing .zshrc symlink" && exit 1)
+          test -L "$XDG_CONFIG_HOME/.config/nvim/init.lua" || (echo "Missing Neovim config" && exit 1)
       - name: Show final structure
         run: |-
           tree -L 2 $XDG_CONFIG_HOME || true
